app.name: Vertx SprintBoot Demo
app.description: Sample VertxSprintBoot Demo Application

debug: true

spring.profiles.active: production
spring.application.name: ${app.name} (${spring.profiles.active})

vertx.http.port: 9080

server.context-path: /vertx-springboot
server.port: 9000
server.use-forward-headers: true
server.compression.enabled: true

#security.user.name: john_doe
#security.user.password: mysupersecretpassword

management.security.enabled: false
management.port: 9001
management.context-path: /manage